clean: true
author: 'MOBGEN Technology'
author_url: 'https://mobgen.com'
module: 'Halo'
module_version: 2.2.0
output: docs
xcodebuild_arguments: [-project, ../Halo.xcodeproj, -scheme, Halo iOS]
source_directory: Sources
copyright: '2016 MOBGEN Technology'
github_url: https://github.com/mobgen/halo-ios
github_file_prefix: https://github.com/mobgen/halo-ios/tree/2.2.0
skip_undocumented: true
hide_documentation_coverage: true
theme: fullwidth